SVGs as static files
galaniprojects/Polkadot-Bounty-Manager pull request #363
Opened 2024-11-28 12:48 UTC by arty-name

2024-11-28 13:24 UTC, BlertaSunCacti requested changes

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/Footer.svelte
> +		<img width="307" height="62" src={LogoBountyManagerDesktop} alt="Logo" />
The width and height are already part of the svg file I reckon. We could therefore spare them here.

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/app-bar/AppBar.svelte
> +			<img width="71" height="54" src={LogoBountyManagerMobile} alt="Logo" />
Same thing as above.

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/common/Dialog.svelte
> +						<img src={CloseIcon} alt="Close icon" height="30" width="30" />
Here too.

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/curator-actions/child-bounties/operations/AddChildBounty.svelte
> +				<img src={PolkaCoin} width="20" height="20" alt="PolkaCoin" />
Here as well.

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/curator-actions/child-bounties/operations/AssignSubCurator.svelte
> +				<img src={PolkaCoin} width="20" height="20" alt="PolkaCoin" />
See above.

2024-11-28 13:24 UTC, BlertaSunCacti commented on src/components/curator-actions/child-bounties/operations/BatchChildBountyCalls.svelte
> +				<img src={PolkaCoin} width="20" height="20" alt="PolkaCoin" />
Once more.

2024-11-28 14:35 UTC, arty-name commented
@BlertaSunCacti, it is recommended to always provide a size for an image either via such attributes or via CSS, because otherwise the browser will initially render the page with just a small placeholder, and once the image loads and its intrinsic dimensions become known, the browser will re-render everything in different sizes resulting in "jumping" content. This is called [Layout Shift](https://web.dev/articles/cls) and is an important metric of website quality.

2024-11-28 16:08 UTC, abdulmth approved these changes

2024-11-29 09:00 UTC, BlertaSunCacti approved these changes

2024-11-29 09:05 UTC, merged