add bounty bond and transaction fee
galaniprojects/Polkadot-Bounty-Manager pull request #44
Opened 2024-08-02 13:47 UTC by BlertaSunCacti

Fixes #9

2024-08-02 14:11 UTC, abdulmth requested changes

2024-08-02 14:11 UTC, abdulmth commented on src/app.css
> +  color: #28123E;
we should add colors to the file `tailwind.config.js` and reference them from there using something like: 
`background-color: theme(colors.gray.100);`

2024-08-02 14:11 UTC, abdulmth commented on src/components/bounty-setup/BountyCreation.svelte
> +			<div class="deposit mt-5 mb-10 h-24">
where is the `deposit` class defined?

2024-08-02 14:11 UTC, abdulmth commented on src/components/bounty-setup/BountyCreation.svelte
> +		background-color:rgba(155,133,177,0.2);
same thing here, colors is better defined in the tailwind config file.

2024-08-02 14:35 UTC, BlertaSunCacti commented on src/components/bounty-setup/BountyCreation.svelte
> +			<div class="deposit mt-5 mb-10 h-24">
Will remove it. It was a mistake.

2024-08-06 07:56 UTC, abdulmth approved these changes

2024-08-06 07:56 UTC, merged